/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Template } from './Template';

export const SEED_TEMPLATES: Template[] = [
  // 1. BEAT SYNC / TRENDING
  {
    id: 'tmpl_velocity_beat',
    name: 'Velocity Beat Sync',
    category: 'beat_sync',
    description: 'Fast-paced kinetic velocity cuts mapped to high-energy electronic kick and snare transients.',
    thumbnail: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&auto=format&fit=crop&q=80',
    previewVideoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    duration: '00:15',
    durationSeconds: 15,
    aspectRatio: '9:16',
    width: 1080,
    height: 1920,
    fps: 60,
    style: 'Fast',
    tags: ['Beat Sync', 'Velocity', 'TikTok', 'Speed Ramp', 'Cyberpunk'],
    creator: { name: 'Alex Rivera', handle: '@rivera_edits', verified: true },
    usageCount: 248900,
    likesCount: 19400,
    rating: 4.9,
    isTrending: true,
    isNew: false,
    isStaffPick: true,
    createdAt: '2026-08-15T12:00:00Z',
    colorPalette: ['#06b6d4', '#f43f5e', '#3b82f6'],
    transitions: ['Whip Pan', 'Flash Cut', 'Zoom In Blur'],
    effects: ['RGB Split Glitch', 'Motion Blur', 'Bass Shake'],
    filters: ['Teal & Orange Blockbuster', 'High Contrast'],
    audioTrack: {
      id: 'mus_velocity_drop',
      title: 'Neon Overdrive Drop (140 BPM)',
      artist: 'Kroma Sound Lab',
      durationSeconds: 15,
      bpm: 140,
      url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
      beatMarkers: [0.0, 1.28, 2.57, 3.85, 5.14, 6.42, 7.71, 9.0, 10.28, 11.57, 12.85, 14.14],
    },
    mediaSlots: [
      {
        id: 'slot_1',
        slotIndex: 0,
        name: 'Opening Hook Clip',
        type: 'video',
        startTimeSeconds: 0.0,
        durationSeconds: 1.28,
        label: 'Clip 1 (Hook)',
        defaultUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&auto=format&fit=crop&q=80',
        cropBehavior: 'cover',
      },
      {
        id: 'slot_2',
        slotIndex: 1,
        name: 'Speed Build 1',
        type: 'video',
        startTimeSeconds: 1.28,
        durationSeconds: 1.29,
        label: 'Clip 2 (Build)',
        defaultUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=400&auto=format&fit=crop&q=80',
        cropBehavior: 'cover',
      },
      {
        id: 'slot_3',
        slotIndex: 2,
        name: 'Bass Drop Impact',
        type: 'video',
        startTimeSeconds: 2.57,
        durationSeconds: 1.28,
        label: 'Clip 3 (Drop)',
        defaultUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=400&auto=format&fit=crop&q=80',
        cropBehavior: 'cover',
      },
      {
        id: 'slot_4',
        slotIndex: 3,
        name: 'Action Motion 1',
        type: 'video',
        startTimeSeconds: 3.85,
        durationSeconds: 2.57,
        label: 'Clip 4 (Action)',
        defaultUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&auto=format&fit=crop&q=80',
        cropBehavior: 'cover',
      },
      {
        id: 'slot_5',
        slotIndex: 4,
        name: 'Flash Cut 2',
        type: 'video',
        startTimeSeconds: 6.42,
        durationSeconds: 2.58,
        label: 'Clip 5 (Ramp)',
        defaultUrl: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=400&auto=format&fit=crop&q=80',
        cropBehavior: 'cover',
      },
      {
        id: 'slot_6',
        slotIndex: 5,
        name: 'Outro Finale',
        type: 'video',
        startTimeSeconds: 9.0,
        durationSeconds: 6.0,
        label: 'Clip 6 (Finale)',
        defaultUrl: 'https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?w=400&auto=format&fit=crop&q=80',
        cropBehavior: 'cover',
      },
    ],
    textSlots: [
      {
        id: 'text_1',
        slotIndex: 0,
        name: 'Main Title',
        defaultText: 'VELOCITY FLOW',
        startTimeSeconds: 0.2,
        durationSeconds: 2.0,
        fontFamily: 'Montserrat',
        fontSize: 72,
        fontWeight: '900',
        color: '#ffffff',
        alignment: 'center',
        animation: 'pop',
        glowColor: '#06b6d4',
        glowIntensity: 0.8,
      },
      {
        id: 'text_2',
        slotIndex: 1,
        name: 'Subtitle Hook',
        defaultText: 'DROP THE BASS',
        startTimeSeconds: 2.57,
        durationSeconds: 2.2,
        fontFamily: 'Impact',
        fontSize: 48,
        fontWeight: '800',
        color: '#fde047',
        alignment: 'center',
        animation: 'zoom-in',
      },
    ],
  },

  // 2. CINEMATIC
  {
    id: 'tmpl_cinematic_nordic',
    name: 'Nordic Cinematic Film',
    category: 'cinematic',
    description: 'Slow anamorphic landscape sweeps with 35mm film grain, letterbox ratio, and orchestral emotional swells.',
    thumbnail: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80',
    previewVideoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    duration: '00:24',
    durationSeconds: 24,
    aspectRatio: '16:9',
    width: 1920,
    height: 1080,
    fps: 24,
    style: 'Cinematic',
    tags: ['Cinematic', 'Nordic', 'Landscape', '35mm Film', 'Film Grain', '4K'],
    creator: { name: 'Elena Vane', handle: '@elena_cine', verified: true },
    usageCount: 182400,
    likesCount: 16200,
    rating: 4.95,
    isTrending: true,
    isNew: false,
    isStaffPick: true,
    createdAt: '2026-08-10T10:00:00Z',
    colorPalette: ['#1e293b', '#0f766e', '#f59e0b'],
    transitions: ['Slow Cross Dissolve', 'Film Burn Dissolve', 'Optical Fade to Black'],
    effects: ['35mm Film Grain', 'Anamorphic Flare', 'Subtle Vignette'],
    filters: ['Kodak 35mm Film Grade', 'Muted Highlights'],
    audioTrack: {
      id: 'mus_nordic_strings',
      title: 'Aura of the Fjords (Cinematic Strings)',
      artist: 'Lumina Chamber Ensemble',
      durationSeconds: 24,
      bpm: 72,
      url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    },
    mediaSlots: [
      {
        id: 'slot_1',
        slotIndex: 0,
        name: 'Opening Mountain Vista',
        type: 'video',
        startTimeSeconds: 0.0,
        durationSeconds: 6.0,
        label: 'Wide Shot 1 (Opening)',
        defaultUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1200&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_2',
        slotIndex: 1,
        name: 'Glacier Drone Pan',
        type: 'video',
        startTimeSeconds: 6.0,
        durationSeconds: 6.0,
        label: 'Drone Pan 2',
        defaultUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_3',
        slotIndex: 2,
        name: 'Close Waterfall Detail',
        type: 'video',
        startTimeSeconds: 12.0,
        durationSeconds: 6.0,
        label: 'Detail Shot 3',
        defaultUrl: 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=1200&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_4',
        slotIndex: 3,
        name: 'Sunset Climax Master',
        type: 'video',
        startTimeSeconds: 18.0,
        durationSeconds: 6.0,
        label: 'Golden Hour Climax 4',
        defaultUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400&auto=format&fit=crop&q=80',
      },
    ],
    textSlots: [
      {
        id: 'text_1',
        slotIndex: 0,
        name: 'Location Title',
        defaultText: 'THE NORTHERN REALM',
        startTimeSeconds: 1.0,
        durationSeconds: 4.5,
        fontFamily: 'Cinzel',
        fontSize: 54,
        fontWeight: '600',
        color: '#f8fafc',
        alignment: 'center',
        letterSpacing: 8,
        animation: 'fade',
      },
      {
        id: 'text_2',
        slotIndex: 1,
        name: 'Director / Tagline',
        defaultText: 'A CINEMATIC ODYSSEY',
        startTimeSeconds: 19.0,
        durationSeconds: 4.0,
        fontFamily: 'Montserrat',
        fontSize: 24,
        fontWeight: '500',
        color: '#cbd5e1',
        alignment: 'center',
        letterSpacing: 6,
        animation: 'fade',
      },
    ],
  },

  // 3. REELS & TIKTOK
  {
    id: 'tmpl_viral_hook_reels',
    name: 'Viral 3-Second Hook Reel',
    category: 'reels',
    description: 'Proven high-retention vertical layout featuring top text hook banner, auto karaoke subtitles, and fast jump cuts.',
    thumbnail: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&auto=format&fit=crop&q=80',
    duration: '00:12',
    durationSeconds: 12,
    aspectRatio: '9:16',
    width: 1080,
    height: 1920,
    fps: 60,
    style: 'Fast',
    tags: ['Reels', 'TikTok', 'Shorts', 'Viral Hook', 'Karaoke Subtitles'],
    creator: { name: 'Mia Chen', handle: '@miacreates', verified: true },
    usageCount: 310500,
    likesCount: 28400,
    rating: 4.88,
    isTrending: true,
    isNew: false,
    createdAt: '2026-08-18T14:00:00Z',
    colorPalette: ['#f43f5e', '#ffffff', '#000000'],
    transitions: ['Quick Zoom', 'Whip Up', 'Cut'],
    effects: ['Subtle Dynamic Shake', 'Punch In Zoom'],
    filters: ['Clean Portrait Glow', 'Vibrant Warmth'],
    audioTrack: {
      id: 'mus_viral_pop',
      title: 'Trending Aesthetic Lo-Fi Beat',
      artist: 'VeeSound Studio',
      durationSeconds: 12,
      bpm: 110,
      url: '',
    },
    mediaSlots: [
      {
        id: 'slot_1',
        slotIndex: 0,
        name: 'Hook Video 1',
        type: 'video',
        startTimeSeconds: 0.0,
        durationSeconds: 3.0,
        label: '3s Main Hook',
        defaultUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_2',
        slotIndex: 1,
        name: 'Supporting Point 1',
        type: 'video',
        startTimeSeconds: 3.0,
        durationSeconds: 3.0,
        label: 'Step 1 Clip',
        defaultUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_3',
        slotIndex: 2,
        name: 'Supporting Point 2',
        type: 'video',
        startTimeSeconds: 6.0,
        durationSeconds: 3.0,
        label: 'Step 2 Clip',
        defaultUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_4',
        slotIndex: 3,
        name: 'Call to Action Outro',
        type: 'video',
        startTimeSeconds: 9.0,
        durationSeconds: 3.0,
        label: 'Call to Action',
        defaultUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&auto=format&fit=crop&q=80',
      },
    ],
    textSlots: [
      {
        id: 'text_1',
        slotIndex: 0,
        name: 'Header Hook Banner',
        defaultText: 'STOP MAKING THIS MISTAKE 🛑',
        startTimeSeconds: 0.0,
        durationSeconds: 12.0,
        fontFamily: 'Montserrat',
        fontSize: 38,
        fontWeight: '900',
        color: '#ffffff',
        backgroundColor: '#000000',
        backgroundOpacity: 0.85,
        alignment: 'center',
        positionY: 150,
      },
      {
        id: 'text_2',
        slotIndex: 1,
        name: 'Call To Action',
        defaultText: 'Save this for later & Follow! ✨',
        startTimeSeconds: 8.5,
        durationSeconds: 3.5,
        fontFamily: 'Inter',
        fontSize: 32,
        fontWeight: '700',
        color: '#fde047',
        alignment: 'center',
        positionY: 1600,
        animation: 'bounce',
      },
    ],
  },

  // 4. AI TEMPLATES
  {
    id: 'tmpl_ai_neural_montage',
    name: 'AI Neural Smart Montage',
    category: 'ai_templates',
    description: 'AI-assisted intelligent clip sequencing with automatic face centering, dynamic speed ramps, and neural color matching.',
    thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80',
    duration: '00:18',
    durationSeconds: 18,
    aspectRatio: '9:16',
    width: 1080,
    height: 1920,
    fps: 60,
    style: 'Aesthetic',
    tags: ['AI Templates', 'Neural Montage', 'Auto Reframe', 'Smart Cuts', 'Gemini'],
    creator: { name: 'VeeCut Neural AI', verified: true },
    usageCount: 142000,
    likesCount: 12900,
    rating: 4.98,
    isTrending: true,
    isNew: true,
    isAIPowered: true,
    aiFeatures: ['Auto Face Tracking', 'Neural Color Grading', 'AI Audio Beat Snapping'],
    createdAt: '2026-08-25T09:00:00Z',
    colorPalette: ['#38bdf8', '#818cf8', '#c084fc'],
    transitions: ['Morph Dissolve', 'Neural Warp', 'AI Light Streak'],
    effects: ['AI Depth Bokeh', 'Dynamic Chromatic Aberration'],
    filters: ['Parametric Studio LUT', 'AI Skin Smoothing'],
    mediaSlots: [
      {
        id: 'slot_1',
        slotIndex: 0,
        name: 'Opening Subject',
        type: 'any',
        startTimeSeconds: 0.0,
        durationSeconds: 3.6,
        label: 'Subject Clip 1',
        defaultUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_2',
        slotIndex: 1,
        name: 'Action Focus 2',
        type: 'any',
        startTimeSeconds: 3.6,
        durationSeconds: 3.6,
        label: 'Subject Clip 2',
        defaultUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_3',
        slotIndex: 2,
        name: 'Motion Arc 3',
        type: 'any',
        startTimeSeconds: 7.2,
        durationSeconds: 3.6,
        label: 'Subject Clip 3',
        defaultUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_4',
        slotIndex: 3,
        name: 'Close Emotion 4',
        type: 'any',
        startTimeSeconds: 10.8,
        durationSeconds: 3.6,
        label: 'Subject Clip 4',
        defaultUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_5',
        slotIndex: 4,
        name: 'AI Reveal Outro',
        type: 'any',
        startTimeSeconds: 14.4,
        durationSeconds: 3.6,
        label: 'Outro Clip 5',
        defaultUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
      },
    ],
    textSlots: [
      {
        id: 'text_1',
        slotIndex: 0,
        name: 'AI Vision Headline',
        defaultText: 'POWERED BY AI',
        startTimeSeconds: 0.5,
        durationSeconds: 3.0,
        fontFamily: 'Montserrat',
        fontSize: 48,
        fontWeight: '900',
        color: '#38bdf8',
        alignment: 'center',
        glowColor: '#38bdf8',
        glowIntensity: 0.9,
      },
    ],
  },

  // 5. TRAVEL
  {
    id: 'tmpl_travel_wanderlust',
    name: 'Wanderlust Destination Diary',
    category: 'travel',
    description: 'Dynamic holiday diary with passport stamps, location stamps, smooth zoom map transitions, and summer color grades.',
    thumbnail: 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800&auto=format&fit=crop&q=80',
    duration: '00:20',
    durationSeconds: 20,
    aspectRatio: '9:16',
    width: 1080,
    height: 1920,
    fps: 60,
    style: 'Aesthetic',
    tags: ['Travel', 'Wanderlust', 'Vacation', 'Montage', 'Summer', 'Diary'],
    creator: { name: 'Marco Rossi', handle: '@marcotravels', verified: true },
    usageCount: 168400,
    likesCount: 14100,
    rating: 4.92,
    isTrending: true,
    isNew: false,
    createdAt: '2026-08-12T11:00:00Z',
    colorPalette: ['#0ea5e9', '#f59e0b', '#10b981'],
    transitions: ['Smooth Push Left', 'Zoom Out', 'Light Leak'],
    effects: ['Summer Warm Glow', 'Soft Vignette'],
    filters: ['Fuji Velvia Vivid', 'Golden Hour Glow'],
    mediaSlots: [
      {
        id: 'slot_1',
        slotIndex: 0,
        name: 'Departure Airport / Transit',
        type: 'video',
        startTimeSeconds: 0.0,
        durationSeconds: 4.0,
        label: 'Transit / Departure',
        defaultUrl: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_2',
        slotIndex: 1,
        name: 'Ocean Coastline',
        type: 'video',
        startTimeSeconds: 4.0,
        durationSeconds: 4.0,
        label: 'Coastal Horizon',
        defaultUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_3',
        slotIndex: 2,
        name: 'Local Streets & Food',
        type: 'video',
        startTimeSeconds: 8.0,
        durationSeconds: 4.0,
        label: 'Culture & Dining',
        defaultUrl: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_4',
        slotIndex: 3,
        name: 'Sunset Viewpoint',
        type: 'video',
        startTimeSeconds: 12.0,
        durationSeconds: 4.0,
        label: 'Golden Hour View',
        defaultUrl: 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_5',
        slotIndex: 4,
        name: 'Night Lights Finale',
        type: 'video',
        startTimeSeconds: 16.0,
        durationSeconds: 4.0,
        label: 'Night Finale',
        defaultUrl: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=400&auto=format&fit=crop&q=80',
      },
    ],
    textSlots: [
      {
        id: 'text_1',
        slotIndex: 0,
        name: 'Destination Name',
        defaultText: 'AMALFI COAST, ITALY 🇮🇹',
        startTimeSeconds: 0.5,
        durationSeconds: 3.5,
        fontFamily: 'Playfair Display',
        fontSize: 42,
        fontWeight: '700',
        color: '#ffffff',
        alignment: 'center',
        letterSpacing: 4,
      },
      {
        id: 'text_2',
        slotIndex: 1,
        name: 'Date / Memories Tag',
        defaultText: 'Summer Memories • Vol. 04',
        startTimeSeconds: 16.0,
        durationSeconds: 3.8,
        fontFamily: 'Montserrat',
        fontSize: 26,
        fontWeight: '600',
        color: '#fef08a',
        alignment: 'center',
      },
    ],
  },

  // 6. YOUTUBE / WIDESCREEN
  {
    id: 'tmpl_youtube_modern_intro',
    name: 'YouTube Modern Video Essay',
    category: 'youtube',
    description: 'Clean widescreen 16:9 intro with chapter card overlays, lower thirds, author badges, and minimal typography.',
    thumbnail: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&auto=format&fit=crop&q=80',
    duration: '00:30',
    durationSeconds: 30,
    aspectRatio: '16:9',
    width: 1920,
    height: 1080,
    fps: 60,
    style: 'Professional',
    tags: ['YouTube', 'Video Essay', 'Intro', 'Lower Thirds', 'Widescreen'],
    creator: { name: 'David Miller', handle: '@davidtech', verified: true },
    usageCount: 94500,
    likesCount: 8200,
    rating: 4.85,
    isTrending: false,
    isNew: true,
    createdAt: '2026-08-20T16:00:00Z',
    colorPalette: ['#1e1b4b', '#6366f1', '#e0e7ff'],
    transitions: ['Clean Slide Left', 'Minimal Cut', 'Cross Dissolve'],
    effects: ['Soft Drop Shadows', 'Clean Studio Glow'],
    filters: ['Clean Digital Rec.709', 'Natural Skin Tone'],
    mediaSlots: [
      {
        id: 'slot_1',
        slotIndex: 0,
        name: 'Presenter A-Roll Hook',
        type: 'video',
        startTimeSeconds: 0.0,
        durationSeconds: 10.0,
        label: 'A-Roll Hook',
        defaultUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1200&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_2',
        slotIndex: 1,
        name: 'B-Roll Evidence 1',
        type: 'video',
        startTimeSeconds: 10.0,
        durationSeconds: 10.0,
        label: 'B-Roll Supporting 1',
        defaultUrl: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=1200&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_3',
        slotIndex: 2,
        name: 'B-Roll Evidence 2',
        type: 'video',
        startTimeSeconds: 20.0,
        durationSeconds: 10.0,
        label: 'B-Roll Supporting 2',
        defaultUrl: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=1200&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=400&auto=format&fit=crop&q=80',
      },
    ],
    textSlots: [
      {
        id: 'text_1',
        slotIndex: 0,
        name: 'Episode Title',
        defaultText: 'THE FUTURE OF ARTIFICIAL CREATIVITY',
        startTimeSeconds: 1.0,
        durationSeconds: 6.0,
        fontFamily: 'Inter',
        fontSize: 48,
        fontWeight: '800',
        color: '#ffffff',
        alignment: 'left',
        positionX: 120,
        positionY: 820,
      },
      {
        id: 'text_2',
        slotIndex: 1,
        name: 'Speaker Lower Third',
        defaultText: 'DAVID MILLER • TECH RESEARCHER',
        startTimeSeconds: 2.0,
        durationSeconds: 5.0,
        fontFamily: 'Montserrat',
        fontSize: 22,
        fontWeight: '600',
        color: '#818cf8',
        alignment: 'left',
        positionX: 120,
        positionY: 900,
      },
    ],
  },

  // 7. GAMING
  {
    id: 'tmpl_gaming_clutch',
    name: 'Esports Clutch Montage',
    category: 'gaming',
    description: 'High-octane gaming montage with bass impact shakes, neon kill counters, flash transitions, and streamer cam PIP.',
    thumbnail: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop&q=80',
    duration: '00:15',
    durationSeconds: 15,
    aspectRatio: '16:9',
    width: 1920,
    height: 1080,
    fps: 60,
    style: 'Energetic',
    tags: ['Gaming', 'Esports', 'Montage', 'Valorant', 'Clutch', 'Kill Sync'],
    creator: { name: 'KAIZEN GAMING', handle: '@kaizen_fps', verified: true },
    usageCount: 135200,
    likesCount: 11800,
    rating: 4.91,
    isTrending: true,
    isNew: false,
    createdAt: '2026-08-16T18:00:00Z',
    colorPalette: ['#a855f7', '#06b6d4', '#ef4444'],
    transitions: ['RGB Warp', 'Flash Cut', 'Strobe Zoom'],
    effects: ['Screen Shake', 'Chroma Split', 'Cyberpunk Grid'],
    filters: ['Neon Tokyo Grade', 'Saturated Highlights'],
    mediaSlots: [
      {
        id: 'slot_1',
        slotIndex: 0,
        name: 'Setup / Angle Hold',
        type: 'video',
        startTimeSeconds: 0.0,
        durationSeconds: 3.0,
        label: 'Clutch Setup',
        defaultUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1200&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_2',
        slotIndex: 1,
        name: 'First Kill Transient',
        type: 'video',
        startTimeSeconds: 3.0,
        durationSeconds: 3.0,
        label: 'Kill 1 (Fast)',
        defaultUrl: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=1200&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_3',
        slotIndex: 2,
        name: 'Flick Kill 2',
        type: 'video',
        startTimeSeconds: 6.0,
        durationSeconds: 3.0,
        label: 'Kill 2 (Flick)',
        defaultUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1200&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_4',
        slotIndex: 3,
        name: 'Final Round Win Climax',
        type: 'video',
        startTimeSeconds: 9.0,
        durationSeconds: 6.0,
        label: 'Ace / Victory Climax',
        defaultUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1200&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=400&auto=format&fit=crop&q=80',
      },
    ],
    textSlots: [
      {
        id: 'text_1',
        slotIndex: 0,
        name: 'Clutch Banner',
        defaultText: '1v4 CLUTCH ACE 🏆',
        startTimeSeconds: 0.2,
        durationSeconds: 3.5,
        fontFamily: 'Montserrat',
        fontSize: 64,
        fontWeight: '900',
        color: '#a855f7',
        alignment: 'center',
        glowColor: '#c084fc',
        glowIntensity: 0.9,
      },
    ],
  },

  // 8. PRODUCT PROMO / BUSINESS
  {
    id: 'tmpl_product_showcase',
    name: 'Sleek Product Commercial',
    category: 'product_promo',
    description: 'Commercial advertisement layout with clean 3D product rotations, discount callout tags, feature bullet badges, and CTA outro.',
    thumbnail: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80',
    duration: '00:15',
    durationSeconds: 15,
    aspectRatio: '1:1',
    width: 1080,
    height: 1080,
    fps: 60,
    style: 'Professional',
    tags: ['Product Promo', 'Commercial', 'E-Commerce', 'Shopify', 'Clean Minimal'],
    creator: { name: 'Studio Vertex', handle: '@vertexads', verified: true },
    usageCount: 88400,
    likesCount: 7600,
    rating: 4.89,
    isTrending: false,
    isNew: true,
    isStaffPick: true,
    createdAt: '2026-08-22T10:00:00Z',
    colorPalette: ['#14b8a6', '#0f172a', '#f8fafc'],
    transitions: ['Clean Swipe', 'Cross Dissolve', 'Scale Pop'],
    effects: ['Subtle Shadow Floor', 'Studio Light Reflection'],
    filters: ['Clean Product Neutral', 'Crisp Edge Sharpening'],
    mediaSlots: [
      {
        id: 'slot_1',
        slotIndex: 0,
        name: 'Product Hero Angle',
        type: 'any',
        startTimeSeconds: 0.0,
        durationSeconds: 5.0,
        label: 'Hero Angle',
        defaultUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_2',
        slotIndex: 1,
        name: 'Feature Close-Up',
        type: 'any',
        startTimeSeconds: 5.0,
        durationSeconds: 5.0,
        label: 'Feature Detail',
        defaultUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_3',
        slotIndex: 2,
        name: 'Lifestyle In-Use',
        type: 'any',
        startTimeSeconds: 10.0,
        durationSeconds: 5.0,
        label: 'Lifestyle / CTA',
        defaultUrl: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=400&auto=format&fit=crop&q=80',
      },
    ],
    textSlots: [
      {
        id: 'text_1',
        slotIndex: 0,
        name: 'Product Brand / Model',
        defaultText: 'AURA PRO WIRELESS',
        startTimeSeconds: 0.5,
        durationSeconds: 4.5,
        fontFamily: 'Montserrat',
        fontSize: 44,
        fontWeight: '800',
        color: '#ffffff',
        alignment: 'center',
        positionY: 880,
      },
      {
        id: 'text_2',
        slotIndex: 1,
        name: 'Key Feature',
        defaultText: 'Active Noise Cancellation • 40hr Battery',
        startTimeSeconds: 5.5,
        durationSeconds: 4.5,
        fontFamily: 'Inter',
        fontSize: 26,
        fontWeight: '600',
        color: '#2dd4bf',
        alignment: 'center',
        positionY: 880,
      },
      {
        id: 'text_3',
        slotIndex: 2,
        name: 'Discount & CTA',
        defaultText: 'SHOP NOW — 30% OFF',
        startTimeSeconds: 10.5,
        durationSeconds: 4.5,
        fontFamily: 'Montserrat',
        fontSize: 36,
        fontWeight: '900',
        color: '#fde047',
        backgroundColor: '#0f172a',
        alignment: 'center',
        positionY: 880,
      },
    ],
  },

  // 9. WEDDING
  {
    id: 'tmpl_wedding_elegance',
    name: 'Timeless Wedding Romance',
    category: 'wedding',
    description: 'Soft golden bokeh, slow-motion dissolves, classical piano score, and serif typography for timeless wedding memories.',
    thumbnail: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=800&auto=format&fit=crop&q=80',
    duration: '00:30',
    durationSeconds: 30,
    aspectRatio: '16:9',
    width: 1920,
    height: 1080,
    fps: 24,
    style: 'Emotional',
    tags: ['Wedding', 'Romantic', 'Elegance', 'Golden Hour', 'Memories'],
    creator: { name: 'Claire Dubois', handle: '@claireweddingfilms', verified: true },
    usageCount: 72100,
    likesCount: 6800,
    rating: 4.97,
    isTrending: false,
    isNew: false,
    createdAt: '2026-08-05T14:00:00Z',
    colorPalette: ['#fef3c7', '#fde047', '#78350f'],
    transitions: ['Soft White Flash Dissolve', 'Slow Cross Fade', 'Golden Light Leak'],
    effects: ['Golden Bokeh Particles', 'Soft Diffuse Glow'],
    filters: ['Warm Romantic Gold LUT', 'Soft Highlight Roll-off'],
    mediaSlots: [
      {
        id: 'slot_1',
        slotIndex: 0,
        name: 'Getting Ready / Rings',
        type: 'any',
        startTimeSeconds: 0.0,
        durationSeconds: 7.5,
        label: 'Ring & Vow Prep',
        defaultUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=1200&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_2',
        slotIndex: 1,
        name: 'First Look / Ceremony',
        type: 'any',
        startTimeSeconds: 7.5,
        durationSeconds: 7.5,
        label: 'Ceremony Walk',
        defaultUrl: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=1200&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_3',
        slotIndex: 2,
        name: 'Golden Hour Portrait',
        type: 'any',
        startTimeSeconds: 15.0,
        durationSeconds: 7.5,
        label: 'Sunset Couple Portrait',
        defaultUrl: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=1200&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_4',
        slotIndex: 3,
        name: 'First Dance Reception',
        type: 'any',
        startTimeSeconds: 22.5,
        durationSeconds: 7.5,
        label: 'First Dance',
        defaultUrl: 'https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?w=1200&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?w=400&auto=format&fit=crop&q=80',
      },
    ],
    textSlots: [
      {
        id: 'text_1',
        slotIndex: 0,
        name: 'Couples Names',
        defaultText: 'EMMA & LIAM',
        startTimeSeconds: 1.0,
        durationSeconds: 6.0,
        fontFamily: 'Playfair Display',
        fontSize: 56,
        fontWeight: '600',
        color: '#fef3c7',
        alignment: 'center',
        letterSpacing: 8,
      },
      {
        id: 'text_2',
        slotIndex: 1,
        name: 'Wedding Date',
        defaultText: 'AUGUST 24, 2026 • LAKE COMO',
        startTimeSeconds: 23.0,
        durationSeconds: 6.0,
        fontFamily: 'Montserrat',
        fontSize: 22,
        fontWeight: '500',
        color: '#fde68a',
        alignment: 'center',
        letterSpacing: 6,
      },
    ],
  },

  // 10. BIRTHDAY
  {
    id: 'tmpl_birthday_party',
    name: 'Birthday Celebration Magic',
    category: 'birthday',
    description: 'Vibrant confetti bursts, glowing balloon badges, festive music sync, and personalized photo slideshow memory frames.',
    thumbnail: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800&auto=format&fit=crop&q=80',
    duration: '00:15',
    durationSeconds: 15,
    aspectRatio: '9:16',
    width: 1080,
    height: 1920,
    fps: 60,
    style: 'Energetic',
    tags: ['Birthday', 'Celebration', 'Party', 'Photo Slideshow', 'Confetti'],
    creator: { name: 'PartyVibes Media', handle: '@partyvibes', verified: true },
    usageCount: 65400,
    likesCount: 5200,
    rating: 4.84,
    isTrending: false,
    isNew: true,
    createdAt: '2026-08-21T15:00:00Z',
    colorPalette: ['#ec4899', '#facc15', '#38bdf8'],
    transitions: ['Confetti Pop Cut', 'Whip Right', 'Scale Bounce'],
    effects: ['Confetti Rain', 'Sparkle Stars'],
    filters: ['Vivid Birthday Pop', 'Warm Skin Tones'],
    mediaSlots: [
      {
        id: 'slot_1',
        slotIndex: 0,
        name: 'Birthday Star Opening',
        type: 'any',
        startTimeSeconds: 0.0,
        durationSeconds: 3.75,
        label: 'Hero Birthday Smile',
        defaultUrl: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_2',
        slotIndex: 1,
        name: 'Cake & Candle Blow',
        type: 'any',
        startTimeSeconds: 3.75,
        durationSeconds: 3.75,
        label: 'Cake & Candle',
        defaultUrl: 'https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_3',
        slotIndex: 2,
        name: 'Friends & Family Cheering',
        type: 'any',
        startTimeSeconds: 7.5,
        durationSeconds: 3.75,
        label: 'Party Moments',
        defaultUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_4',
        slotIndex: 3,
        name: 'Memory Cheers Outro',
        type: 'any',
        startTimeSeconds: 11.25,
        durationSeconds: 3.75,
        label: 'Finale Cheers',
        defaultUrl: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=400&auto=format&fit=crop&q=80',
      },
    ],
    textSlots: [
      {
        id: 'text_1',
        slotIndex: 0,
        name: 'Birthday Greeting',
        defaultText: 'HAPPY BIRTHDAY SOPHIA! 🎂🎉',
        startTimeSeconds: 0.5,
        durationSeconds: 3.2,
        fontFamily: 'Montserrat',
        fontSize: 44,
        fontWeight: '900',
        color: '#fde047',
        alignment: 'center',
        animation: 'bounce',
      },
      {
        id: 'text_2',
        slotIndex: 1,
        name: 'Age / Wishes Tagline',
        defaultText: 'Cheers to 25 Years of Magic ✨',
        startTimeSeconds: 11.5,
        durationSeconds: 3.2,
        fontFamily: 'Playfair Display',
        fontSize: 32,
        fontWeight: '700',
        color: '#fbcfe8',
        alignment: 'center',
      },
    ],
  },

  // 11. SPORTS
  {
    id: 'tmpl_sports_hype',
    name: 'Apex Athletic Hype Reel',
    category: 'sports',
    description: 'High-impact speed ramps, aggressive bass drop hits, flash flares, and bold italicized athletic typography for workouts and athletes.',
    thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80',
    duration: '00:15',
    durationSeconds: 15,
    aspectRatio: '9:16',
    width: 1080,
    height: 1920,
    fps: 60,
    style: 'Energetic',
    tags: ['Sports', 'Fitness', 'Gym', 'Workout', 'Hype', 'Football', 'Basketball'],
    creator: { name: 'Tyson Apex', handle: '@tysonfitness', verified: true },
    usageCount: 112000,
    likesCount: 9400,
    rating: 4.88,
    isTrending: true,
    isNew: false,
    createdAt: '2026-08-14T08:00:00Z',
    colorPalette: ['#f97316', '#ef4444', '#000000'],
    transitions: ['Impact Whip Left', 'Strobe Flash', 'Zoom Push'],
    effects: ['Sub Bass Camera Shake', 'High Velocity Motion Blur'],
    filters: ['Gritty Desaturated Action LUT', 'High Contrast Black Crush'],
    mediaSlots: [
      {
        id: 'slot_1',
        slotIndex: 0,
        name: 'Pre-Game Focus',
        type: 'video',
        startTimeSeconds: 0.0,
        durationSeconds: 3.75,
        label: 'Focus Shot 1',
        defaultUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_2',
        slotIndex: 1,
        name: 'Sprint / Lift Ramp',
        type: 'video',
        startTimeSeconds: 3.75,
        durationSeconds: 3.75,
        label: 'Action Ramp 2',
        defaultUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_3',
        slotIndex: 2,
        name: 'Climax Impact Goal/Rep',
        type: 'video',
        startTimeSeconds: 7.5,
        durationSeconds: 3.75,
        label: 'Climax Impact 3',
        defaultUrl: 'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_4',
        slotIndex: 3,
        name: 'Victory Celebration',
        type: 'video',
        startTimeSeconds: 11.25,
        durationSeconds: 3.75,
        label: 'Victory Outro 4',
        defaultUrl: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=400&auto=format&fit=crop&q=80',
      },
    ],
    textSlots: [
      {
        id: 'text_1',
        slotIndex: 0,
        name: 'Hype Motto',
        defaultText: 'UNSTOPPABLE.',
        startTimeSeconds: 0.2,
        durationSeconds: 3.5,
        fontFamily: 'Montserrat',
        fontSize: 58,
        fontWeight: '900',
        color: '#f97316',
        alignment: 'center',
      },
    ],
  },

  // 12. VLOG / MINIMAL
  {
    id: 'tmpl_vlog_cozy',
    name: 'Cozy Morning Routine Vlog',
    category: 'vlog',
    description: 'Aesthetic minimal vlog layout with cozy warm neutrals, paper texture borders, timestamp clocks, and relaxing lo-fi pacing.',
    thumbnail: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&auto=format&fit=crop&q=80',
    duration: '00:20',
    durationSeconds: 20,
    aspectRatio: '9:16',
    width: 1080,
    height: 1920,
    fps: 30,
    style: 'Minimal',
    tags: ['Vlog', 'Routine', 'Cozy', 'Minimal', 'Coffee', 'Aesthetic'],
    creator: { name: 'Hana Tanaka', handle: '@hanalifestyle', verified: true },
    usageCount: 89000,
    likesCount: 7800,
    rating: 4.93,
    isTrending: false,
    isNew: true,
    createdAt: '2026-08-23T11:00:00Z',
    colorPalette: ['#d6d3d1', '#78716c', '#44403c'],
    transitions: ['Soft Cross Fade', 'Dip to White', 'Minimal Slide'],
    effects: ['Soft Vignette', 'Subtle 16mm Dust'],
    filters: ['Warm Latte LUT', 'Soft Film Curve'],
    mediaSlots: [
      {
        id: 'slot_1',
        slotIndex: 0,
        name: 'Wake Up / Sunrise Light',
        type: 'any',
        startTimeSeconds: 0.0,
        durationSeconds: 5.0,
        label: '07:00 AM Sunrise',
        defaultUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_2',
        slotIndex: 1,
        name: 'Brewing Coffee / Matcha',
        type: 'any',
        startTimeSeconds: 5.0,
        durationSeconds: 5.0,
        label: 'Coffee Pouring',
        defaultUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_3',
        slotIndex: 2,
        name: 'Reading / Journaling',
        type: 'any',
        startTimeSeconds: 10.0,
        durationSeconds: 5.0,
        label: 'Journal & Desk',
        defaultUrl: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_4',
        slotIndex: 3,
        name: 'Step Outside',
        type: 'any',
        startTimeSeconds: 15.0,
        durationSeconds: 5.0,
        label: 'Outro Walk',
        defaultUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400&auto=format&fit=crop&q=80',
      },
    ],
    textSlots: [
      {
        id: 'text_1',
        slotIndex: 0,
        name: 'Time Stamp',
        defaultText: '07:30 AM • Sunday Routine',
        startTimeSeconds: 0.5,
        durationSeconds: 4.5,
        fontFamily: 'Montserrat',
        fontSize: 28,
        fontWeight: '500',
        color: '#f5f5f4',
        alignment: 'left',
        positionX: 100,
        positionY: 200,
      },
      {
        id: 'text_2',
        slotIndex: 1,
        name: 'Reflection Tagline',
        defaultText: 'slow mornings & warm coffee ☕',
        startTimeSeconds: 15.2,
        durationSeconds: 4.5,
        fontFamily: 'Playfair Display',
        fontSize: 32,
        fontWeight: '600',
        color: '#fafaf9',
        alignment: 'center',
      },
    ],
  },

  // 13. BUSINESS / CORPORATE
  {
    id: 'tmpl_business_pitch',
    name: 'Corporate Brand Pitch & Metrics',
    category: 'business',
    description: 'Executive corporate presentation layout with animated KPI stats, modern blue gradients, team callouts, and clean brand logo reveal.',
    thumbnail: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&auto=format&fit=crop&q=80',
    duration: '00:30',
    durationSeconds: 30,
    aspectRatio: '16:9',
    width: 1920,
    height: 1080,
    fps: 60,
    style: 'Professional',
    tags: ['Business', 'Corporate', 'Pitch', 'SaaS', 'Finance', 'Metrics'],
    creator: { name: 'Nexus Media Lab', handle: '@nexuscorporate', verified: true },
    usageCount: 54100,
    likesCount: 4200,
    rating: 4.88,
    isTrending: false,
    isNew: false,
    createdAt: '2026-08-01T12:00:00Z',
    colorPalette: ['#1e40af', '#3b82f6', '#93c5fd'],
    transitions: ['Precision Slide Left', 'Fade Over Dark', 'Linear Wipe'],
    effects: ['Subtle Grid Line Glow', 'Clean Depth Blur'],
    filters: ['Crisp Corporate Rec.709', 'Clean Whites'],
    mediaSlots: [
      {
        id: 'slot_1',
        slotIndex: 0,
        name: 'Corporate HQ Skyline',
        type: 'any',
        startTimeSeconds: 0.0,
        durationSeconds: 10.0,
        label: 'Company Overview',
        defaultUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_2',
        slotIndex: 1,
        name: 'Team Collaboration',
        type: 'any',
        startTimeSeconds: 10.0,
        durationSeconds: 10.0,
        label: 'Team & Innovation',
        defaultUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1200&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_3',
        slotIndex: 2,
        name: 'Customer Success / Impact',
        type: 'any',
        startTimeSeconds: 20.0,
        durationSeconds: 10.0,
        label: 'Results & Contact',
        defaultUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=400&auto=format&fit=crop&q=80',
      },
    ],
    textSlots: [
      {
        id: 'text_1',
        slotIndex: 0,
        name: 'Company Mission',
        defaultText: 'INNOVATION AT SCALE',
        startTimeSeconds: 1.0,
        durationSeconds: 8.0,
        fontFamily: 'Montserrat',
        fontSize: 48,
        fontWeight: '800',
        color: '#ffffff',
        alignment: 'left',
        positionX: 120,
        positionY: 820,
      },
      {
        id: 'text_2',
        slotIndex: 1,
        name: 'Key Metric Stat',
        defaultText: '+142% ANNUAL GROWTH • 10M+ USERS',
        startTimeSeconds: 11.0,
        durationSeconds: 8.0,
        fontFamily: 'Inter',
        fontSize: 32,
        fontWeight: '700',
        color: '#60a5fa',
        alignment: 'left',
        positionX: 120,
        positionY: 820,
      },
    ],
  },

  // 14. PHOTOGRAPHY
  {
    id: 'tmpl_photo_contact_sheet',
    name: '35mm Film Portfolio Reel',
    category: 'photography',
    description: 'Analog contact sheet film border aesthetic with sprocket holes, photo zoom pans, subtle light leaks, and minimalist shutter clicks.',
    thumbnail: 'https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=800&auto=format&fit=crop&q=80',
    duration: '00:16',
    durationSeconds: 16,
    aspectRatio: '4:5',
    width: 1080,
    height: 1350,
    fps: 30,
    style: 'Aesthetic',
    tags: ['Photography', 'Portfolio', '35mm', 'Contact Sheet', 'Analog', 'Film'],
    creator: { name: 'Julian Gray', handle: '@juliangray_photo', verified: true },
    usageCount: 49200,
    likesCount: 4600,
    rating: 4.96,
    isTrending: false,
    isNew: true,
    createdAt: '2026-08-24T13:00:00Z',
    colorPalette: ['#262626', '#a3a3a3', '#fafafa'],
    transitions: ['Shutter Flash Cut', 'Film Slide', 'Soft Cross Fade'],
    effects: ['Film Border Overlay', 'Subtle Dust & Scratches'],
    filters: ['Tri-X Black & White Contrast', 'Rich Midtones'],
    mediaSlots: [
      {
        id: 'slot_1',
        slotIndex: 0,
        name: 'Portfolio Frame 1',
        type: 'image',
        startTimeSeconds: 0.0,
        durationSeconds: 4.0,
        label: 'Photo 1 (Portrait)',
        defaultUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_2',
        slotIndex: 1,
        name: 'Portfolio Frame 2',
        type: 'image',
        startTimeSeconds: 4.0,
        durationSeconds: 4.0,
        label: 'Photo 2 (Architecture)',
        defaultUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_3',
        slotIndex: 2,
        name: 'Portfolio Frame 3',
        type: 'image',
        startTimeSeconds: 8.0,
        durationSeconds: 4.0,
        label: 'Photo 3 (Street)',
        defaultUrl: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_4',
        slotIndex: 3,
        name: 'Portfolio Frame 4',
        type: 'image',
        startTimeSeconds: 12.0,
        durationSeconds: 4.0,
        label: 'Photo 4 (Landscape)',
        defaultUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=400&auto=format&fit=crop&q=80',
      },
    ],
    textSlots: [
      {
        id: 'text_1',
        slotIndex: 0,
        name: 'Photographer Name',
        defaultText: 'JULIAN GRAY • 35MM SELECTIONS',
        startTimeSeconds: 0.5,
        durationSeconds: 15.0,
        fontFamily: 'Montserrat',
        fontSize: 24,
        fontWeight: '600',
        color: '#e5e5e5',
        alignment: 'center',
        positionY: 1250,
        letterSpacing: 4,
      },
    ],
  },

  // 15. LYRICS / MUSIC
  {
    id: 'tmpl_lyrics_neon_glow',
    name: 'Kinetic Neon Lyric Glow',
    category: 'lyrics_music',
    description: 'Dynamic word-by-word karaoke typography synced to audio rhythm with cyberpunk neon glows and reactive soundwaves.',
    thumbnail: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&auto=format&fit=crop&q=80',
    duration: '00:15',
    durationSeconds: 15,
    aspectRatio: '9:16',
    width: 1080,
    height: 1920,
    fps: 60,
    style: 'Energetic',
    tags: ['Lyrics', 'Music', 'Karaoke', 'Kinetic Typography', 'Neon Glow'],
    creator: { name: 'SoundWave Visuals', handle: '@soundwavefx', verified: true },
    usageCount: 104000,
    likesCount: 9100,
    rating: 4.9,
    isTrending: true,
    isNew: false,
    createdAt: '2026-08-17T17:00:00Z',
    colorPalette: ['#c084fc', '#f43f5e', '#38bdf8'],
    transitions: ['Glitch Cut', 'Whip Blur', 'Zoom Pulse'],
    effects: ['Neon Lyric Glow', 'Audio Reactive Pulse'],
    filters: ['Cyberpunk Synthwave Grade'],
    mediaSlots: [
      {
        id: 'slot_1',
        slotIndex: 0,
        name: 'Music Visualizer Backdrop',
        type: 'video',
        startTimeSeconds: 0.0,
        durationSeconds: 15.0,
        label: 'Background Canvas',
        defaultUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&auto=format&fit=crop&q=80',
      },
    ],
    textSlots: [
      {
        id: 'text_1',
        slotIndex: 0,
        name: 'Line 1 Lyrics',
        defaultText: 'LOST IN THE CITY LIGHTS 🌃',
        startTimeSeconds: 0.5,
        durationSeconds: 3.5,
        fontFamily: 'Montserrat',
        fontSize: 48,
        fontWeight: '900',
        color: '#c084fc',
        alignment: 'center',
        glowColor: '#c084fc',
        glowIntensity: 0.9,
      },
      {
        id: 'text_2',
        slotIndex: 1,
        name: 'Line 2 Lyrics',
        defaultText: 'RUNNING OUT OF TIME ⏳',
        startTimeSeconds: 4.0,
        durationSeconds: 3.5,
        fontFamily: 'Montserrat',
        fontSize: 48,
        fontWeight: '900',
        color: '#38bdf8',
        alignment: 'center',
        glowColor: '#38bdf8',
        glowIntensity: 0.9,
      },
      {
        id: 'text_3',
        slotIndex: 2,
        name: 'Chorus Climax',
        defaultText: 'WE OWN THE NIGHT ✨',
        startTimeSeconds: 7.5,
        durationSeconds: 7.0,
        fontFamily: 'Montserrat',
        fontSize: 54,
        fontWeight: '900',
        color: '#f43f5e',
        alignment: 'center',
        glowColor: '#f43f5e',
        glowIntensity: 1.0,
      },
    ],
  },

  // 16. MEMES
  {
    id: 'tmpl_meme_comedy_zoom',
    name: 'Dramatic Zoom Meme Cut',
    category: 'memes',
    description: 'Fast humorous dramatic zoom cut with sound gag cues, caption speech bubbles, and instant freeze-frame rewind.',
    thumbnail: 'https://images.unsplash.com/photo-1534972195531-a756b1126f24?w=800&auto=format&fit=crop&q=80',
    duration: '00:08',
    durationSeconds: 8,
    aspectRatio: '9:16',
    width: 1080,
    height: 1920,
    fps: 60,
    style: 'Humorous',
    tags: ['Memes', 'Comedy', 'Viral Gag', 'Dramatic Zoom', 'Punchline'],
    creator: { name: 'MemeForge Lab', handle: '@memeforge', verified: true },
    usageCount: 215000,
    likesCount: 18700,
    rating: 4.87,
    isTrending: true,
    isNew: false,
    createdAt: '2026-08-19T20:00:00Z',
    colorPalette: ['#84cc16', '#ffffff', '#000000'],
    transitions: ['Dramatic Snap Zoom In', 'Vinyl Scratch Cut'],
    effects: ['Freeze Frame BW', 'Bass Distort'],
    filters: ['Viral TikTok High Saturation'],
    mediaSlots: [
      {
        id: 'slot_1',
        slotIndex: 0,
        name: 'Normal Setup Moment',
        type: 'any',
        startTimeSeconds: 0.0,
        durationSeconds: 4.0,
        label: 'Setup Moment',
        defaultUrl: 'https://images.unsplash.com/photo-1534972195531-a756b1126f24?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1534972195531-a756b1126f24?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_2',
        slotIndex: 1,
        name: 'Punchline Sudden Zoom',
        type: 'any',
        startTimeSeconds: 4.0,
        durationSeconds: 4.0,
        label: 'Punchline Reaction',
        defaultUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
      },
    ],
    textSlots: [
      {
        id: 'text_1',
        slotIndex: 0,
        name: 'Setup Premise',
        defaultText: 'Me: "I will go to bed early tonight"',
        startTimeSeconds: 0.0,
        durationSeconds: 4.0,
        fontFamily: 'Montserrat',
        fontSize: 36,
        fontWeight: '800',
        color: '#ffffff',
        backgroundColor: '#000000',
        alignment: 'center',
        positionY: 150,
      },
      {
        id: 'text_2',
        slotIndex: 1,
        name: 'Punchline Reality',
        defaultText: 'Me at 3:45 AM watching cat videos: 💀',
        startTimeSeconds: 4.0,
        durationSeconds: 4.0,
        fontFamily: 'Montserrat',
        fontSize: 36,
        fontWeight: '900',
        color: '#facc15',
        backgroundColor: '#000000',
        alignment: 'center',
        positionY: 150,
      },
    ],
  },

  // 17. MINIMAL
  {
    id: 'tmpl_minimal_type',
    name: 'Swiss Typographic Reel',
    category: 'minimal',
    description: 'Clean Swiss modern design with grid typography, geometric negative space, smooth black and white transitions, and architecture imagery.',
    thumbnail: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&auto=format&fit=crop&q=80',
    duration: '00:15',
    durationSeconds: 15,
    aspectRatio: '9:16',
    width: 1080,
    height: 1920,
    fps: 60,
    style: 'Minimal',
    tags: ['Minimal', 'Swiss Type', 'Modern', 'Clean', 'Design', 'Architecture'],
    creator: { name: 'Atelier Form', handle: '@atelierform', verified: true },
    usageCount: 68900,
    likesCount: 6100,
    rating: 4.95,
    isTrending: false,
    isNew: true,
    isStaffPick: true,
    createdAt: '2026-08-25T10:00:00Z',
    colorPalette: ['#ffffff', '#09090b', '#71717a'],
    transitions: ['Clean Hard Cut', 'Smooth Fade'],
    effects: ['Subtle Grid Overlay'],
    filters: ['Pure Monochrome High Key'],
    mediaSlots: [
      {
        id: 'slot_1',
        slotIndex: 0,
        name: 'Architecture Geometry 1',
        type: 'any',
        startTimeSeconds: 0.0,
        durationSeconds: 5.0,
        label: 'Structure 1',
        defaultUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_2',
        slotIndex: 1,
        name: 'Light & Shadow 2',
        type: 'any',
        startTimeSeconds: 5.0,
        durationSeconds: 5.0,
        label: 'Shadow 2',
        defaultUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_3',
        slotIndex: 2,
        name: 'Interior Detail 3',
        type: 'any',
        startTimeSeconds: 10.0,
        durationSeconds: 5.0,
        label: 'Interior 3',
        defaultUrl: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=400&auto=format&fit=crop&q=80',
      },
    ],
    textSlots: [
      {
        id: 'text_1',
        slotIndex: 0,
        name: 'Design Philosophy',
        defaultText: 'FORM FOLLOWS FUNCTION.',
        startTimeSeconds: 0.5,
        durationSeconds: 14.0,
        fontFamily: 'Inter',
        fontSize: 48,
        fontWeight: '900',
        color: '#ffffff',
        alignment: 'left',
        letterSpacing: 2,
        positionX: 80,
        positionY: 300,
      },
    ],
  },

  // 18. TIKTOK & SHORTS
  {
    id: 'tmpl_tiktok_trending_glow',
    name: 'TikTok Speed Ramp & Flash',
    category: 'tiktok',
    description: 'Fast viral TikTok editing format featuring 0.4s micro-beats, edge glow flares, and rapid photo/video slideshow flips.',
    thumbnail: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
    duration: '00:10',
    durationSeconds: 10,
    aspectRatio: '9:16',
    width: 1080,
    height: 1920,
    fps: 60,
    style: 'Fast',
    tags: ['TikTok', 'Shorts', 'Speed Ramp', 'Flash Cut', 'Micro Cuts'],
    creator: { name: 'Kylie Edits', handle: '@kyliecuts', verified: true },
    usageCount: 198000,
    likesCount: 17400,
    rating: 4.89,
    isTrending: true,
    isNew: false,
    createdAt: '2026-08-16T14:00:00Z',
    colorPalette: ['#06b6d4', '#ec4899'],
    transitions: ['Micro Flash Cut', 'Whip Zoom', 'Edge Glow Transition'],
    effects: ['Edge RGB Flare', 'Speed Blur'],
    filters: ['Neon Saturated Glow'],
    mediaSlots: [
      {
        id: 'slot_1',
        slotIndex: 0,
        name: 'Micro Cut 1',
        type: 'any',
        startTimeSeconds: 0.0,
        durationSeconds: 2.0,
        label: 'Cut 1',
        defaultUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_2',
        slotIndex: 1,
        name: 'Micro Cut 2',
        type: 'any',
        startTimeSeconds: 2.0,
        durationSeconds: 2.0,
        label: 'Cut 2',
        defaultUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_3',
        slotIndex: 2,
        name: 'Micro Cut 3',
        type: 'any',
        startTimeSeconds: 4.0,
        durationSeconds: 2.0,
        label: 'Cut 3',
        defaultUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_4',
        slotIndex: 3,
        name: 'Micro Cut 4',
        type: 'any',
        startTimeSeconds: 6.0,
        durationSeconds: 4.0,
        label: 'Cut 4 Finale',
        defaultUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400&auto=format&fit=crop&q=80',
      },
    ],
    textSlots: [
      {
        id: 'text_1',
        slotIndex: 0,
        name: 'Trending Hook',
        defaultText: 'THIS AUDIO IS GOING VIRAL 🎧',
        startTimeSeconds: 0.2,
        durationSeconds: 3.0,
        fontFamily: 'Montserrat',
        fontSize: 40,
        fontWeight: '900',
        color: '#ffffff',
        alignment: 'center',
        glowColor: '#06b6d4',
        glowIntensity: 0.9,
      },
    ],
  },

  // 19. YOUTUBE SHORTS
  {
    id: 'tmpl_shorts_fact_countdown',
    name: 'Shorts 5-Fact Countdown',
    category: 'youtube_shorts',
    description: 'Fast numbered countdown layout with fact bubbles, high-contrast subtitles, and animated progress timer bar.',
    thumbnail: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&auto=format&fit=crop&q=80',
    duration: '00:15',
    durationSeconds: 15,
    aspectRatio: '9:16',
    width: 1080,
    height: 1920,
    fps: 60,
    style: 'Fast',
    tags: ['YouTube Shorts', 'Countdown', 'Top 5', 'Facts', 'Educational', 'Shorts'],
    creator: { name: 'FactRush', handle: '@factrush', verified: true },
    usageCount: 124000,
    likesCount: 10900,
    rating: 4.88,
    isTrending: true,
    isNew: false,
    createdAt: '2026-08-17T11:00:00Z',
    colorPalette: ['#ef4444', '#facc15', '#ffffff'],
    transitions: ['Quick Push Up', 'Whip Left', 'Hard Cut'],
    effects: ['Timer Progress Bar', 'Attention Glow'],
    filters: ['Vivid Contrast'],
    mediaSlots: [
      {
        id: 'slot_1',
        slotIndex: 0,
        name: 'Fact 1 Visual',
        type: 'any',
        startTimeSeconds: 0.0,
        durationSeconds: 5.0,
        label: 'Fact 1',
        defaultUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_2',
        slotIndex: 1,
        name: 'Fact 2 Visual',
        type: 'any',
        startTimeSeconds: 5.0,
        durationSeconds: 5.0,
        label: 'Fact 2',
        defaultUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_3',
        slotIndex: 2,
        name: 'Fact 3 Climax Visual',
        type: 'any',
        startTimeSeconds: 10.0,
        durationSeconds: 5.0,
        label: 'Fact 3 Finale',
        defaultUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=400&auto=format&fit=crop&q=80',
      },
    ],
    textSlots: [
      {
        id: 'text_1',
        slotIndex: 0,
        name: 'Countdown Title',
        defaultText: 'TOP 3 MIND-BLOWING FACTS 🤯',
        startTimeSeconds: 0.0,
        durationSeconds: 15.0,
        fontFamily: 'Montserrat',
        fontSize: 38,
        fontWeight: '900',
        color: '#ffffff',
        backgroundColor: '#ef4444',
        alignment: 'center',
        positionY: 160,
      },
    ],
  },

  // 20. NEW RELEASES
  {
    id: 'tmpl_new_cyber_glitch',
    name: 'Cyberpunk Neon Matrix 2026',
    category: 'new',
    description: 'Fresh 2026 release with volumetric laser sweeps, RGB matrix glitching, futuristic HUD targets, and synthwave pacing.',
    thumbnail: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800&auto=format&fit=crop&q=80',
    duration: '00:15',
    durationSeconds: 15,
    aspectRatio: '9:16',
    width: 1080,
    height: 1920,
    fps: 60,
    style: 'Energetic',
    tags: ['New', 'Cyberpunk', 'Neon', 'Matrix', 'Glitch', 'HUD'],
    creator: { name: 'NEO VFX', handle: '@neovfx', verified: true },
    usageCount: 31200,
    likesCount: 3900,
    rating: 4.96,
    isTrending: true,
    isNew: true,
    createdAt: '2026-08-28T09:00:00Z',
    colorPalette: ['#06b6d4', '#ec4899', '#8b5cf6'],
    transitions: ['Cyber Glitch', 'RGB Laser Wipe', 'HUD Zoom'],
    effects: ['Matrix Data Rain', 'Volumetric Glow'],
    filters: ['Cyberpunk Tokyo High LUT'],
    mediaSlots: [
      {
        id: 'slot_1',
        slotIndex: 0,
        name: 'Cyber Opening',
        type: 'any',
        startTimeSeconds: 0.0,
        durationSeconds: 5.0,
        label: 'Cyber Scene 1',
        defaultUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_2',
        slotIndex: 1,
        name: 'Neon Streets',
        type: 'any',
        startTimeSeconds: 5.0,
        durationSeconds: 5.0,
        label: 'Cyber Scene 2',
        defaultUrl: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'slot_3',
        slotIndex: 2,
        name: 'Matrix Core Finale',
        type: 'any',
        startTimeSeconds: 10.0,
        durationSeconds: 5.0,
        label: 'Cyber Finale',
        defaultUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&auto=format&fit=crop&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&auto=format&fit=crop&q=80',
      },
    ],
    textSlots: [
      {
        id: 'text_1',
        slotIndex: 0,
        name: 'Cyber Title',
        defaultText: 'SYSTEM OVERRIDE',
        startTimeSeconds: 0.5,
        durationSeconds: 4.5,
        fontFamily: 'Montserrat',
        fontSize: 52,
        fontWeight: '900',
        color: '#06b6d4',
        alignment: 'center',
        glowColor: '#06b6d4',
        glowIntensity: 1.0,
      },
    ],
  },
];
